In [2]:
import numpy as np
import scipy as sp
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline

ModuleNotFoundError: No module named 'seaborn'

# 1. Работа с массивами NumPy

**N. Все упражнения ниже нужно делать без использования циклов Python**

**1.** Cоздать вектор

$$(2, \frac{2^2}{2}, \ldots, \frac{2^{20}}{20})$$

Можно использовать функции [np.arange()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.arange.html), [np.ones()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.ones.html)

In [17]:
## your code
a = np.ones(20)
a *= 2
b = np.arange(1, 21, 1)
d = a ** b
c = d / b

print(c)


[2.00000000e+00 2.00000000e+00 2.66666667e+00 4.00000000e+00
 6.40000000e+00 1.06666667e+01 1.82857143e+01 3.20000000e+01
 5.68888889e+01 1.02400000e+02 1.86181818e+02 3.41333333e+02
 6.30153846e+02 1.17028571e+03 2.18453333e+03 4.09600000e+03
 7.71011765e+03 1.45635556e+04 2.75941053e+04 5.24288000e+04]


**2.** Посчитать:

$$\sum\limits_{i=0}^{5}{0.1^{3i}0.2^{4i}}$$


In [35]:
## your code
a = np.arange(0, 16, 3)
b = np.arange(0, 21, 4)
c = 0.1 ** a
d = 0.2 ** b
e = c * d
print(e.sum())


1.00000160000256


**3.** Создать нулевую матрицe $8 \times 8$, и заполнить её единицами в шахматном порядке.

In [30]:
## your code
m = np.zeros((8, 8), dtype='int64')
a = np.arange(0, 7, 2)
m[0:8, a] = 1
a += 1
m[a, 0:8] = m[a, ::-1] 
print(m)


[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


**4.** Есть 5 точек в декартовой системе координат (в виде матрицы $X$ размерностью $5 \times 2$), сконвертируйте эти точки в полярную систему координат.

In [40]:
X = np.random.random((5, 2))
## your code
q = (X[0] ** 2 + X[1] ** 2) ** 0.5
f = np.arctan(X[0] / X[1])

**5.** Найдите индексы максимального элемента в случайной матрице $10 \times 10$.

Cм. [np.argmax()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.argmax.html).

In [53]:
X = np.random.random((10, 10))

## your code
print(np.argmin(X) // 10, " ", np.argmin(X) % 10)

1   3


**6.** Есть 10 точек ($X$) и ещё одна ($y$). Найти в $X$ ближайшую к $y$ точку.

In [72]:
X = np.random.random((10, 2))
y = np.random.random((1, 2))

## your code
#print(X)
print(np.argmin(X[:,0] * y[0][0] + X[:,1] * y[0][1]))

9


**7.** Дана функция:

$$
 \begin{cases}
    x^2 + 2x + 6, & x < 0  \\
    x + 6, & 0 \le x \le 2 \\
    x^2 + 4x - 4, & x \ge 2
 \end{cases}
$$

Постройте массив из её значений на  $-3 \le x \le 3$.

In [73]:
## your code
@np.vectorize
def foo(x):
    if x < 0:
        return x ** 2 + 2 * x + 6
    if x >= 0 and x <= 2:
        return x + 6
    return x ** 2 + 4 * x - 4

foo(np.arange(-3, 3, 0.1))

array([ 9.  ,  8.61,  8.24,  7.89,  7.56,  7.25,  6.96,  6.69,  6.44,
        6.21,  6.  ,  5.81,  5.64,  5.49,  5.36,  5.25,  5.16,  5.09,
        5.04,  5.01,  5.  ,  5.01,  5.04,  5.09,  5.16,  5.25,  5.36,
        5.49,  5.64,  5.81,  6.  ,  6.1 ,  6.2 ,  6.3 ,  6.4 ,  6.5 ,
        6.6 ,  6.7 ,  6.8 ,  6.9 ,  7.  ,  7.1 ,  7.2 ,  7.3 ,  7.4 ,
        7.5 ,  7.6 ,  7.7 ,  7.8 ,  7.9 ,  8.  ,  8.81,  9.64, 10.49,
       11.36, 12.25, 13.16, 14.09, 15.04, 16.01])

**8.** Из каждого элемента матрицы вычесть среднее арифметическое от всех элементов в соответствующей строке (после чего среднее значение каждой строки должно равняться нулю).

Cм. [np.mean()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.mean.html).

In [14]:
X = np.random.random((10, 10))

## your code
mean = np.mean(X, axis=1)
a = np.ones((10,10))
a *= mean
a = a.T
X -= a
new_mean = np.mean(X, axis=1)
print(new_mean)


[ 1.11022302e-17 -7.77156117e-17 -2.22044605e-17 -1.22124533e-16
 -3.33066907e-17 -2.22044605e-17  5.55111512e-17  2.22044605e-17
  2.22044605e-17 -7.77156117e-17]


**9.** Есть массив из 1000 чисел, полученных из генератора случайных чисел, имеющий нормальное распределение. Посчитайте выборочное среднее и выборочную дисперсию. 

In [13]:
X = np.random.normal(loc=5, scale=2., size=1000)
mean = np.sum(X) / 1000
disp = np.sum(np.square(X)) / 1000 - mean**2
print("disp is ", disp)
print("mean is ", mean)

disp is  4.044799537589647
mean is  5.029990161755859


**10.** Создать матрицу:

$$
\begin{pmatrix}
0 & 1 & 2 & 3 & 4 \\
1 & 2 & 3 & 4 & 0 \\
2 & 3 & 4 & 0 & 1 \\
3 & 4 & 0 & 1 & 2 \\
4 & 0 & 1 & 2 & 3
\end{pmatrix}
$$

In [16]:
## your code
L = np.arange(0, 5, 1)
X = np.zeros((5,5)) + L
r = -1 * np.arange(5)
a, b = np.ogrid[:5, :5]
r[r < 0] += 5
b = b - r[:,np.newaxis]
print(X[a, b])


[[0. 1. 2. 3. 4.]
 [1. 2. 3. 4. 0.]
 [2. 3. 4. 0. 1.]
 [3. 4. 0. 1. 2.]
 [4. 0. 1. 2. 3.]]


**11.** Есть следующий алгоритм семплинирования, на вход функции подается вектор из целых положительных чисел и число семплов.

In [32]:
def sample(x, c):
    assert len(x) > 0
    
    s = np.sum(x)
    res = []
    for _ in range(c):
        val = s * np.random.random()
        cur, idx = 0, 0        
        while cur + x[idx] <= val:
            cur += x[idx]
            idx += 1
            
        res.append(idx)
    return res

            
sample([50, 3, 1, 7, 20], 5)    

[3, 0, 0, 0, 0]

Реализуйте данный алгоритм более оптимальным способом, без использования циклов.

In [54]:
## your code
def sample2(x, c):
    assert len(x) > 0
    
    s = np.sum(x)
    
    val = s * np.random.random(c)
    x_sum = np.cumsum(x)
    x_sum[x_sum < val]
    res = list(np.searchsorted(x_sum, val))
    
    return res

            
sample2([50, 3, 1, 7, 20], 5)  

[3, 0, 0, 0, 4]